name: smarttile
channels:
  - conda-forge
dependencies:
  - python=3.12
  - sqlite>=3.45
  - pdal
  - gdal
  - untwine
  - laspy
  - lazrs-python
  - numpy
  - scipy
  - matplotlib-base
  - fiona
  - pyproj
  - pydantic
  - pydantic-settings
