"""PLY outputs record their CRS as ``comment crs: <value>`` (read by QGIS/MDAL)."""
import sys
from pathlib import Path

import laspy
import numpy as np
import pytest
from laspy.vlrs.known import WktCoordinateSystemVlr
from pyproj import CRS

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
from crs_records import crs_comment_value
from ply_crs import add_crs_comment_to_ply, crs_comment_from_file

STANDARD = CRS.from_epsg(25833).to_wkt("WKT1_GDAL")
ORIGINAL = STANDARD.replace('"ETRS89 / UTM zone 33N"', '"ETRS89 / UTM zone 33N(Meter)"', 1)
COMPOUND = (f'COMPD_CS["ETRS89 / UTM zone 33N + local height",{STANDARD},'
            'VERT_CS["local height",VERT_DATUM["local",2005],UNIT["metre",1],AXIS["Up",UP]]]')


def header_with(wkt):
    header = laspy.LasHeader(point_format=6, version="1.4")
    header.global_encoding.wkt = True
    header.vlrs.append(WktCoordinateSystemVlr(wkt))
    return header


def write_ply(path, body=b"\x00\x01\x02\xff" * 7, comments=()):
    head = ["ply", "format binary_little_endian 1.0", "comment Generated by PDAL", *comments,
            "element vertex 7", "property uchar a", "property uchar b", "property uchar c", "property uchar d",
            "end_header"]
    path.write_bytes(("\n".join(head) + "\n").encode() + body)
    return body


def header_lines(path):
    lines = []
    with path.open("rb") as stream:
        while (line := stream.readline()).rstrip(b"\n") != b"end_header":
            lines.append(line.rstrip(b"\n").decode())
    return lines


def test_identified_crs_is_written_as_epsg_code():
    assert crs_comment_value(header_with(ORIGINAL)) == "EPSG:25833"
    assert crs_comment_value(header_with(STANDARD)) == "EPSG:25833"


def test_unidentified_crs_is_written_as_single_line_wkt():
    value = crs_comment_value(header_with(COMPOUND))
    assert value.startswith('COMPD_CS["ETRS89 / UTM zone 33N + local height"') and "\n" not in value
    assert CRS.from_wkt(value).equals(CRS.from_wkt(COMPOUND))


def test_no_crs_means_no_comment(tmp_path):
    assert crs_comment_value(laspy.LasHeader(point_format=6, version="1.4")) is None
    path = tmp_path / "a.ply"
    body = write_ply(path)
    assert add_crs_comment_to_ply(path, None) is False
    assert path.read_bytes().endswith(body) and "comment crs:" not in path.read_text(errors="ignore")


def test_comment_is_inserted_after_format_and_payload_is_unchanged(tmp_path):
    path = tmp_path / "product.ply"
    body = write_ply(path)
    assert add_crs_comment_to_ply(path, "EPSG:25833")
    assert header_lines(path)[:3] == ["ply", "format binary_little_endian 1.0", "comment crs: EPSG:25833"]
    assert path.read_bytes().endswith(b"end_header\n" + body)


def test_existing_crs_comment_is_replaced_not_duplicated(tmp_path):
    path = tmp_path / "product.ply"
    body = write_ply(path, comments=["comment crs: EPSG:4326"])
    add_crs_comment_to_ply(path, "EPSG:25833")
    add_crs_comment_to_ply(path, "EPSG:25833")
    assert [l for l in header_lines(path) if l.startswith("comment crs:")] == ["comment crs: EPSG:25833"]
    assert path.read_bytes().endswith(body)


def test_rejects_non_ply_input_and_leaves_it_untouched(tmp_path):
    path = tmp_path / "not.ply"
    path.write_bytes(b"hello\nworld\n")
    with pytest.raises(ValueError):
        add_crs_comment_to_ply(path, "EPSG:25833")
    assert path.read_bytes() == b"hello\nworld\n"
    assert not list(tmp_path.glob(".*"))


def test_crs_comment_from_las_file(tmp_path):
    path = tmp_path / "cloud.las"
    las = laspy.LasData(header_with(ORIGINAL))
    las.x, las.y, las.z = np.array([450000.0]), np.array([5600000.0]), np.array([100.0])
    las.write(path)
    assert crs_comment_from_file(path) == "EPSG:25833"
